import {
  Link,
  ExternalLink,
  Mail,
  Phone,
  Calendar,
  MapPin,
  ShoppingCart,
  BookOpen,
  Video,
  Music,
  Camera,
  Users,
  Code,
  Github,
  Twitter,
  Linkedin,
  Instagram,
  Facebook,
  Youtube,
  MessageCircle,
  Globe,
  Heart,
  Star,
  Zap,
  Coffee,
  Gamepad2,
  Headphones,
  Mic,
  Play,
  Download,
  Share2,
  Gift,
  Award,
  Target,
  Briefcase,
  GraduationCap,
  Home,
  Building,
  Car,
  Plane,
  Utensils,
  FileText,
  Folder,
  Database,
  Server,
  Smartphone,
  Laptop,
  Monitor,
  Settings,
  Lock,
  Key,
  Shield,
  Eye,
  EyeOff,
  Search,
  Grid,
  BarChart3,
  TrendingUp,
  Activity,
  Clock,
  Bell,
  Volume2,
  RefreshCw,
  Power,
  LogIn,
  LogOut,
  UserPlus,
  UserCheck,
  Crown,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Percent,
  DollarSign,
  CreditCard,
  ShoppingBag,
  Package,
  Truck,
  Navigation,
  Compass,
  Map,
  Ship,
  Train,
  Bus,
  Bike,
  Mountain,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Flower,
  Leaf,
  Bug,
  Fish,
  Bird,
  Dog,
  Cat
} from 'lucide-react';

// Icon mapping for different icon values
const iconMap: Record<string, any> = {
  // General icons
  'link': Link,
  'external-link': ExternalLink,
  'mail': Mail,
  'phone': Phone,
  'calendar': Calendar,
  'map-pin': MapPin,
  'location': MapPin,
  'shopping-cart': ShoppingCart,
  'shop': ShoppingCart,
  'book-open': BookOpen,
  'blog': BookOpen,
  'video': Video,
  'music': Music,
  'camera': Camera,
  'photos': Camera,
  'users': Users,
  'community': Users,
  'code': Code,
  'globe': Globe,
  'heart': Heart,
  'star': Star,
  'zap': Zap,
  'coffee': Coffee,
  'gamepad': Gamepad2,
  'headphones': Headphones,
  'mic': Mic,
  'play': Play,
  'download': Download,
  'share': Share2,
  'gift': Gift,
  'award': Award,
  'target': Target,
  'briefcase': Briefcase,
  'graduation-cap': GraduationCap,
  'home': Home,
  'building': Building,
  'car': Car,
  'plane': Plane,
  'utensils': Utensils,
  'file-text': FileText,
  'folder': Folder,
  'database': Database,
  'server': Server,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'monitor': Monitor,
  'settings': Settings,
  'lock': Lock,
  'key': Key,
  'shield': Shield,
  'eye': Eye,
  'eye-off': EyeOff,
  'search': Search,
  'grid': Grid,
  'bar-chart': BarChart3,
  'trending-up': TrendingUp,
  'activity': Activity,
  'clock': Clock,
  'bell': Bell,
  'volume': Volume2,
  'refresh': RefreshCw,
  'power': Power,
  'log-in': LogIn,
  'log-out': LogOut,
  'user-plus': UserPlus,
  'user-check': UserCheck,
  'crown': Crown,
  'flag': Flag,
  'bookmark': Bookmark,
  'tag': Tag,
  'hash': Hash,
  'at-sign': AtSign,
  'percent': Percent,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'shopping-bag': ShoppingBag,
  'package': Package,
  'truck': Truck,
  'navigation': Navigation,
  'compass': Compass,
  'map': Map,
  'ship': Ship,
  'train': Train,
  'bus': Bus,
  'bike': Bike,
  'mountain': Mountain,
  'sun': Sun,
  'moon': Moon,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'wind': Wind,
  'flower': Flower,
  'leaf': Leaf,
  'bug': Bug,
  'fish': Fish,
  'bird': Bird,
  'dog': Dog,
  'cat': Cat,

  // Social media icons
  'github': Github,
  'twitter': Twitter,
  'linkedin': Linkedin,
  'instagram': Instagram,
  'facebook': Facebook,
  'youtube': Youtube,
  'discord': MessageCircle, // Using MessageCircle as Discord placeholder
};

export const getIconComponent = (iconName: string) => {
  const IconComponent = iconMap[iconName.toLowerCase()];
  return IconComponent || Link; // Default to Link icon if not found
};

export const getAvailableIcons = () => {
  return Object.keys(iconMap);
};